kind: pipeline
name: usetaxes

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: arm32v7/node:10.14
  volumes:
  - name: data
    path: /tmp/app-build
  commands:
    - npm i -g @angular/cli
    - npm i
    - npm run build
    - cp -R build /tmp/app-build

- name: deploy
  image: zhikiri/rpi-awscli:1.16.79
  volumes:
  - name: data
    path: /tmp/app-build
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret
  commands:
    - aws s3 cp /tmp/app-build/usetaxes s3://usetaxes.zhikiri.info --recursive"

volumes:
- name: data
  temp: {}
